name: CI

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      
      - name: Show SDKS
        run: xcodebuild -showsdks

      # In XCode 12 it will build the simulator with a arm64 CPU.  We don't want this as when
      # we try to combine the simulator with the device build using Lipo we will get an error
      # because both builds have the same CPU archecture.
      - name: Build iOS Simulator
        run: |
          xcodebuild -sdk iphonesimulator -project "Sample Project/CheckBox.xcodeproj" -derivedDataPath build -scheme BEMCheckBox -configuration Release EXCLUDED_ARCHS="arm64"
          ls -la build/Build/Products/Release-iphonesimulator
          ls -la build/Build/Products/Release-iphonesimulator/BEMCheckBox.framework
          lipo -info build/Build/Products/Release-iphonesimulator/BEMCheckBox.framework/BEMCheckBox

      - name: Build iOS Device
        run: |
          xcodebuild -sdk iphoneos -project "Sample Project/CheckBox.xcodeproj" -derivedDataPath build -scheme BEMCheckBox -configuration Release
          ls -la build/Build/Products/Release-iphoneos
          ls -la build/Build/Products/Release-iphoneos/BEMCheckBox.framework
          lipo -info build/Build/Products/Release-iphoneos/BEMCheckBox.framework/BEMCheckBox

      - name: Combine Builds
        run: |
          cp -R build/Build/Products/Release-iphoneos/ Release-fat
          ls -la Release-fat
          ls -la Release-fat/BEMCheckBox.framework/BEMCheckBox

      - name: Build FAT Binary
        run: |
          lipo -create -output  Release-fat/BEMCheckBox.framework/BEMCheckBox build/Build/Products/Release-iphoneos/BEMCheckBox.framework/BEMCheckBox build/Build/Products/Release-iphonesimulator/BEMCheckBox.framework/BEMCheckbox
          lipo -info Release-fat/BEMCheckBox.framework
          file Release-fat/BEMCheckBox.framework
          ls -la Release-fat
          ls -la Release-fat/BEMCheckBox.framework
