name: CI

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      
      - name: Show SDKS
        run: xcodebuild -showsdks

      - name: Build Simulator
        run: |
          xcodebuild -sdk iphonesimulator -project "Sample Project/CheckBox.xcodeproj" -scheme BEMCheckBox -configuration Release -derivedDataPath build
          ls -la
          cd build
          ls -la
          cd Build
          ls -la
          cd Products
          ls -la
          cd Release-iphonesimulator
          ls -la
          cd BEMCheckBox.freamwork
          ls -la