name: CI

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      
      - name: Show SDKS
        run: xcodebuild -showsdks

      - name: Build iOS Simulator
        run: |
          xcodebuild -sdk iphonesimulator -project "Sample Project/CheckBox.xcodeproj" -derivedDataPath build -scheme BEMCheckBox -configuration Release
          ls -la
          cd build
          ls -la
          cd Build
          ls -la
          cd Products
          ls -la
          cd Release-iphonesimulator
          ls -la
          cd BEMCheckBox.framework
          ls -la

      - name: Build iOS Device
        run: |
          xcodebuild -sdk iphoneos -project "Sample Project/CheckBox.xcodeproj" -derivedDataPath build -scheme BEMCheckBox -configuration Release
          ls -la
          cd build
          ls -la
          cd Build
          ls -la
          cd Products
          ls -la
          cd Release-iphoneos
          ls -la
          cd BEMCheckBox.framework
          ls -la

      - name: Combine Builds
        run: |
          cp -R build/Build/Products/Release-iphoneos/ Release-fat
          ls -la
          ls -la Release-fat
          ls -la Release-fat/BEMCheckBox.framework
          cp -R build/Build/Products/Release-iphonesimulator/BEMCheckbox.framework Release-fat/
          ls -la Release-fat/BEMCheckBox.framework

      # - name: Build FAT Binary
      #   run: |
      #     lipo -create -output BEMCheckBox.framework/BEMCheckBox Release-fat/BEMCheckBox.framework/BEMCheckBox Release-iphonesimulator/BEMCheckBox.framework/BEMCheckbox
